-- MySQL Script generated by MySQL Workbench
-- Вт 23 янв 2018 01:55:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gulindb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gulindb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gulindb` DEFAULT CHARACTER SET utf8 ;
USE `gulindb` ;

-- -----------------------------------------------------
-- Table `gulindb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gulindb`.`admin` (
  `adminID` INT NOT NULL,
  `userName` VARCHAR(45) NULL,
  `userPassword` VARCHAR(45) NULL,
  PRIMARY KEY (`adminID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gulindb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gulindb`.`category` (
  `categoryID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gulindb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gulindb`.`post` (
  `postID` INT NOT NULL,
  `text` VARCHAR(1000) NULL,
  `timestamp` DATETIME NULL,
  `title` VARCHAR(45) NULL,
  `categoryID` INT NOT NULL,
  PRIMARY KEY (`postID`, `categoryID`),
  INDEX `fk_post_category1_idx` (`categoryID` ASC),
  CONSTRAINT `fk_post_category1`
    FOREIGN KEY (`categoryID`)
    REFERENCES `gulindb`.`category` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gulindb`.`image_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gulindb`.`image_post` (
  `imagePostID` INT NOT NULL,
  `path` VARCHAR(45) NULL,
  `postID` INT NOT NULL,
  PRIMARY KEY (`imagePostID`, `postID`),
  INDEX `fk_image_post_post_idx` (`postID` ASC),
  CONSTRAINT `fk_image_post_post`
    FOREIGN KEY (`postID`)
    REFERENCES `gulindb`.`post` (`postID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gulindb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gulindb`.`project` (
  `projectID` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`projectID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gulindb`.`image_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gulindb`.`image_project` (
  `imageProjectID` INT NOT NULL,
  `path` VARCHAR(45) NULL,
  `projectID` INT NOT NULL,
  PRIMARY KEY (`imageProjectID`, `projectID`),
  INDEX `fk_image_project_project1_idx` (`projectID` ASC),
  CONSTRAINT `fk_image_project_project1`
    FOREIGN KEY (`projectID`)
    REFERENCES `gulindb`.`project` (`projectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
